# Generated by Django 5.1.2 on 2025-05-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientprofile_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='doctor',
            new_name='doctorprofile',
        ),
    ]
