# Generated by Django 5.2 on 2025-05-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_report_report_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_images',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
